// ─────────────────────────────────────────────
// REAL PROJECT DATA — ARCHIVED FOR FUTURE USE
// These are the actual AISymmetric projects.
// To restore, copy this array into script.js as PROJECTS.
// ─────────────────────────────────────────────
const REAL_PROJECTS = [
  {
    id: 'crm',
    title: 'AISymmetric CRM',
    category: 'apps',
    categoryLabel: 'Application',
    industry: 'Enterprise',
    description: 'A full-featured AI-powered CRM platform built for SMB to mid-market sales teams. Manages pipeline, contacts, and deal velocity with intelligent automation.',
    stack: ['React', 'Node.js', 'Supabase', 'OpenAI', 'Vercel'],
    build_speed: '2 weeks',
    impact: 'Replaces legacy CRM costs — full pipeline + contact management shipped from scratch.',
    url: 'https://aisymmetric-crm.vercel.app/',
    connections: ['psm', 'lead-scoring', 'salesforce-intel'],
    size: 1.3
  },
  {
    id: 'psm',
    title: 'Project & Service Manager',
    category: 'apps',
    categoryLabel: 'Application',
    industry: 'Operations',
    description: 'An intelligent project and service management platform for tracking deliverables, timelines, and resource allocation across client engagements.',
    stack: ['React', 'Node.js', 'PostgreSQL', 'Vercel'],
    build_speed: '5 days',
    impact: 'Streamlines project tracking and client delivery operations in a single platform.',
    url: 'https://aisymmetric-psm.vercel.app/',
    connections: ['crm', 'dashboard-framework'],
    size: 1.1
  },
  {
    id: 'trading-cards',
    title: 'Trading Card Value App',
    category: 'apps',
    categoryLabel: 'Application',
    industry: 'Consumer / Collectibles',
    description: 'Real-time trading card valuation engine that scans, identifies, and prices sports and collectible cards using AI vision and market data feeds.',
    stack: ['React', 'OpenAI Vision', 'Vercel', 'Node.js'],
    build_speed: '48 hours',
    impact: 'Instant AI-powered card identification and live market pricing for collectors.',
    url: 'https://trading-card-value-app.vercel.app/',
    connections: ['roi-calc'],
    size: 0.9
  },
  {
    id: 'rainmaker',
    title: 'Rainmaker Strategy Game',
    category: 'games',
    categoryLabel: 'Game & Simulation',
    industry: 'Strategy / Education',
    description: 'An immersive business strategy simulation game where players build and scale revenue-generating operations. Combines economic modeling with strategic decision-making.',
    stack: ['JavaScript', 'Canvas API', 'Node.js', 'Vercel'],
    build_speed: '2 weeks',
    impact: 'Trains strategic thinking around revenue generation, resource allocation, and market dynamics.',
    url: 'https://rainmakers-game.vercel.app/',
    connections: ['pe-cost-takeout', 'mfg-revenue'],
    size: 1.4
  },
  {
    id: 'roi-calc',
    title: 'ROI Calculator',
    category: 'data',
    categoryLabel: 'Data & Intelligence',
    industry: 'Sales / Finance',
    description: 'An interactive ROI modeling tool that helps enterprise buyers quantify the financial return of AI and technology investments. Configurable by industry and use case.',
    stack: ['React', 'JavaScript', 'Netlify'],
    build_speed: '48 hours',
    impact: 'Accelerates enterprise sales cycles by giving buyers instant, credible ROI projections.',
    url: 'https://roicalculator.aisymmetricsolutions.com/',
    connections: ['dashboard-framework', 'pe-cost-takeout', 'crm'],
    size: 1.0
  },
  {
    id: 'dashboard-framework',
    title: 'AI Dashboard Framework',
    category: 'data',
    categoryLabel: 'Data & Intelligence',
    industry: 'Enterprise / Multi-vertical',
    description: 'A reusable executive dashboard framework with real-time KPI visualization, AI-generated insights, and multi-source data connectors. Built to deploy across client verticals.',
    stack: ['React', 'D3.js', 'OpenAI', 'REST APIs', 'Netlify'],
    build_speed: '1 week',
    impact: 'Foundation for 10+ client dashboard deployments. Reduces new dashboard build time by 70%.',
    url: 'https://revint.aisymmetricsolutions.com/',
    connections: ['roi-calc', 'salesforce-intel', 'mfg-revenue', 'pe-cost-takeout'],
    size: 1.5
  },
  {
    id: 'web-portfolio',
    title: 'Web Portfolio Showcase',
    category: 'web',
    categoryLabel: 'Web Experience',
    industry: 'Marketing / Brand',
    description: 'The official AISymmetric web portfolio — a curated collection of client websites, platforms, and digital experiences showcasing the firm\'s design and engineering range.',
    stack: ['HTML', 'CSS', 'JavaScript', 'Netlify'],
    build_speed: '3 days',
    impact: 'Central showcase driving enterprise inbound — demonstrates full-stack design and engineering capability.',
    url: 'https://webportfolio.aisymmetricsolutions.com/',
    connections: ['tyler-site', 'sauber', 'casimir', 'canoe'],
    size: 1.1
  },
  {
    id: 'canoe',
    title: 'Canoe Wild Rice — Brand Site',
    category: 'web',
    categoryLabel: 'Web Experience',
    industry: 'CPG / Food & Beverage',
    description: 'A premium brand website for a heritage wild rice company — combining cultural storytelling, product education, and e-commerce with a handcrafted aesthetic.',
    stack: ['HTML', 'CSS', 'JavaScript', 'Netlify'],
    build_speed: '5 days',
    impact: 'Elevated brand presence and online sales channel for an artisanal food producer.',
    url: 'https://canoe-wild-rice.netlify.app/',
    connections: ['web-portfolio', 'sauber'],
    size: 0.85
  },
  {
    id: 'sauber',
    title: 'Sauber Real Estate',
    category: 'web',
    categoryLabel: 'Web Experience',
    industry: 'Real Estate',
    description: 'A sophisticated real estate agency website with property search, agent profiles, and lead capture — built for modern buyer and seller journeys.',
    stack: ['HTML', 'CSS', 'JavaScript', 'Netlify'],
    build_speed: '5 days',
    impact: 'Full-featured real estate web presence with integrated lead generation.',
    url: 'https://sauber-real-estate.netlify.app/',
    connections: ['rockbrook', 'web-portfolio'],
    size: 0.85
  },
  {
    id: 'rockbrook',
    title: 'Rockbrook Real Estate Platform',
    category: 'web',
    categoryLabel: 'Web Experience',
    industry: 'Real Estate',
    description: 'A full IDX real estate platform for property search, listing management, and buyer engagement — built on modern web architecture with AI-powered property recommendations.',
    stack: ['React', 'IDX API', 'Node.js', 'Netlify'],
    build_speed: '2 weeks',
    impact: 'End-to-end property discovery platform powering active buyer and seller transactions.',
    url: 'https://rockbrook.aisymmetricsolutions.com/',
    connections: ['sauber', 'crm'],
    size: 1.1
  },
  {
    id: 'tyler-site',
    title: 'tylerperleberg.com',
    category: 'web',
    categoryLabel: 'Web Experience',
    industry: 'Personal Brand',
    description: 'Executive personal brand platform for Tyler Perleberg — showcasing 20 years of digital leadership, AI expertise, and enterprise transformation experience.',
    stack: ['HTML', 'CSS', 'JavaScript', 'Netlify'],
    build_speed: '3 days',
    impact: 'Premier executive presence driving speaking, advisory, and strategic partnership opportunities.',
    url: 'https://tylerperleberg.com/',
    connections: ['web-portfolio', 'agentforce'],
    size: 1.0
  },
  {
    id: 'casimir',
    title: 'Casimir Basketball',
    category: 'web',
    categoryLabel: 'Web Experience',
    industry: 'Sports / Youth Athletics',
    description: 'A dynamic basketball program website featuring schedules, player profiles, coaching staff, and registration flows for a competitive youth program.',
    stack: ['HTML', 'CSS', 'JavaScript', 'Netlify'],
    build_speed: '48 hours',
    impact: 'Community sports platform enabling program growth and parent/athlete engagement.',
    url: 'https://casimirbasketball.com/',
    connections: ['web-portfolio', 'canoe'],
    size: 0.8
  },
  {
    id: 'agentforce',
    title: 'Agentforce Intelligence Hub',
    category: 'ai',
    categoryLabel: 'AI Agent System',
    industry: 'Enterprise / Salesforce',
    description: 'An intelligent Salesforce Agentforce showcase and demonstration platform — illustrating how AI agents automate enterprise workflows, service operations, and revenue intelligence.',
    stack: ['Salesforce', 'Agentforce', 'OpenAI', 'Node.js'],
    build_speed: '1 week',
    impact: 'Live demonstration of enterprise AI agent capabilities for CRM and service automation.',
    url: 'https://agentforce.tylerperleberg.com/',
    connections: ['salesforce-intel', 'crm', 'tyler-site'],
    size: 1.3
  },
  {
    id: 'harvey-hotel',
    title: 'Harvey Hotel',
    category: 'web',
    categoryLabel: 'Web Experience',
    industry: 'Hospitality',
    description: 'A premium hospitality website for Harvey Hotel — featuring room showcases, booking experiences, local guide content, and brand storytelling for a boutique property.',
    stack: ['HTML', 'CSS', 'JavaScript', 'Netlify'],
    build_speed: '5 days',
    impact: 'Premium hospitality digital presence driving direct bookings and guest engagement.',
    url: 'https://harveyhottel.aisymmetricsolutions.com/',
    connections: ['web-portfolio', 'nordic-sauna'],
    size: 0.9
  },
  {
    id: 'nordic-sauna',
    title: 'Nordic Heat Saunas',
    category: 'web',
    categoryLabel: 'Web Experience',
    industry: 'Health & Wellness / E-Commerce',
    description: 'A premium product and e-commerce website for a Nordic sauna brand — blending wellness storytelling, product education, and conversion-optimized shopping experiences.',
    stack: ['HTML', 'CSS', 'JavaScript', 'E-commerce', 'Netlify'],
    build_speed: '5 days',
    impact: 'Premium DTC e-commerce and brand experience driving sauna product sales.',
    url: 'https://nordicheatsaunas.com/',
    connections: ['web-portfolio', 'harvey-hotel'],
    size: 0.9
  },
  {
    id: 'salesforce-intel',
    title: 'Salesforce Lead Intelligence',
    category: 'ai',
    categoryLabel: 'AI Agent System',
    industry: 'Enterprise Sales',
    description: 'AI-powered lead scoring and pipeline intelligence layer built on Salesforce — using predictive models to rank leads, surface opportunities, and automate outreach sequencing.',
    stack: ['Salesforce', 'Apex', 'OpenAI', 'Python'],
    build_speed: '2 weeks',
    impact: 'Increases pipeline conversion rate and reduces sales rep time spent on manual qualification.',
    url: 'https://aisymmetricsolutions.com/#case-studies',
    connections: ['crm', 'dashboard-framework', 'agentforce'],
    size: 1.2
  },
  {
    id: 'pe-cost-takeout',
    title: 'Cost Takeout Intelligence Engine',
    category: 'data',
    categoryLabel: 'Data & Intelligence',
    industry: 'Private Equity / Finance',
    description: 'A private equity-grade cost analysis platform that maps operating expenses, identifies reduction opportunities, and models savings scenarios across portfolio companies.',
    stack: ['Python', 'React', 'PostgreSQL', 'OpenAI', 'D3.js'],
    build_speed: '1 week',
    impact: 'Enables PE operating partners to identify cost reduction opportunities across portfolio holdings.',
    url: 'https://aisymmetricsolutions.com/#case-studies',
    connections: ['dashboard-framework', 'mfg-revenue', 'rainmaker'],
    size: 1.2
  },
  {
    id: 'mfg-revenue',
    title: 'Manufacturing Revenue Planner',
    category: 'data',
    categoryLabel: 'Data & Intelligence',
    industry: 'Manufacturing',
    description: 'An AI-powered revenue planning system for global manufacturers — integrating demand forecasting, pipeline data, and market signals into executive decision dashboards.',
    stack: ['Python', 'Salesforce', 'React', 'Snowflake', 'OpenAI'],
    build_speed: '2 weeks',
    impact: '40% operational efficiency gain and 2.5x pipeline velocity increase for global manufacturer.',
    url: 'https://aisymmetricsolutions.com/#case-studies',
    connections: ['dashboard-framework', 'salesforce-intel', 'pe-cost-takeout'],
    size: 1.3
  }
];
